name = "Outremonde"
author = "Culsans"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a67c99a8419c345a2cf133d89f9fd072b0620766021d94465edc01cf0c8edcf"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
