name = "Outremonde"
author = "Culsans"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ca627e54949c44ddff96d8335389db53c16030b5ecee4ba4cf6e8bfe0f63f3a"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
